module partial_prd_gen #(parameter MAX_MLTCND_BITS=12, parameter MAX_MLTPLR_BITS=9)(
  multiplicand, multiplier, partial_prd
);

input [MAX_MLTCND_BITS-1 : 0] multiplicand;
input [MAX_MLTPLR_BITS-1 : 0] multiplier;

output [MAX_MLTCND_BITS-1:0] partial_prd[MAX_MLTPLR_BITS-1:0];

// Partial Product generated by anding the multipliers and multiplicand bits
genvar i,j;
generate for(i=0; i<MAX_MLTPLR_BITS; i=i+1) begin
  for(j=0; j<MAX_MLTCND_BITS; j=j+1) begin
    assign partial_prd[i][j] = multiplicand[j] & multiplier[i];
  end
  end
endgenerate

endmodule
